### ISSUE TITLE
CDCF

### ISSUE THREAD

**Issue by CoralieGold** [imac2018-3d/StoneEdge#1]
## Unresolved/important questions : 
- **How do we manage the translation to english ?** If it's unpractical, we should ask teacher about it.

## Main checklist
- [x] Sommaire
- [x] Introduction
- [x] Périmètre du projet
- [x] Utilisation / Gameplay
- [x] Médias
  - [x] Charte graphique
  - [x] Zoning
  - [x] Storyboard
- [x] Cas d'utilisation
- [x] Résumé des fonctionnalités
- [x] Développement futur

**Comment by firegreen** [comment]
This is not a part of my work

**Comment by yoanlcq** [comment]
Thinking this through, a tracking issue for this seems rather clumsy because, in Docs, we can just run through red text and fix comments one by one. If a part of the CDCF is not complete yet, we can just insert a red `TODO` text explaining what's missing, or leave a comment.  
Also checkboxes are too like "true-false" while what we really need is some description of what actually remains to do, and I believe it's best done in Docs while we're at it.  

In any case I hardly see ourselves hopping back and forth from Docs to GitHub for this. However, GitHub issues are pretty good for content requests, as [#3](https://github.com/imac2018-3d/StoneEdge/issues/3) shows.

On the other hand we can't simply close this issue because otherwise we would instantly reach the CDCF milestone.
