### ISSUE TITLE
Prototype: Menus / HUD - Settings

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#14]
Menu design and settings

- [X] Navigate between scenes
- [X] Exit game
--------------------------------
- [X] Load game
- [X] New game
- [X] Save game
--------------------------------
- [x] Main menu
- [x] Break menu
- [x] Character presentation
- [x] Lore items
- [x] Credits
- [x] Settings

**Comment by yoanlcq** [comment]
Useful Hollow Knight keyboard settings screenshot : 
![image](https://raw.githubusercontent.com/imac2018-3d/Screenshots/master/hk_keyboard.jpg)

There's one for gamepad too, but since I don't have one plugged right now, it doesn't display anything. But the menu is essentially the same.    
I might check this when I'm back in my flat this evening, if I don't forget.
