### ISSUE TITLE
Cinematics

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#28]
Pause the world and the hero
Play the camera and the animation
Resume game

**Comment by yoanlcq** [comment]
Also, voting to close this because:

- pause/resume is part of the pause menu functionality (it's essentially done)
- I find that "Play the camera and the animation" is not clear enough; what would the assignee be expected to do ? Surely we will have several cinematics but it won't make sense until we get the game to a working state

**Comment by firegreen** [comment]
agreed
