### ISSUE TITLE
Artwork for CDCF

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#3]
Need some artworks for:
- [x] Main character
- [x] Places where the player can go
- [ ] Enemies
- [x] Attacks
- [ ] moves
- [ ] Story in general

**Comment by firegreen** [comment]
![artwork1](https://user-images.githubusercontent.com/8926916/31866566-cd51821e-b781-11e7-9099-aed1a6515e28.jpeg)

**Comment by firegreen** [comment]
![artwork2](https://user-images.githubusercontent.com/8926916/31867197-246b4cf2-b78b-11e7-9043-8e914c48b003.jpeg)

**Comment by firegreen** [comment]
![artwork3](https://user-images.githubusercontent.com/8926916/31883759-2ed31c14-b7eb-11e7-8787-8fda6dd1aa1d.jpeg)

**Comment by firegreen** [comment]
![artwork4](https://user-images.githubusercontent.com/8926916/31891413-a23cd904-b806-11e7-85d1-e81dd1cb9180.jpeg)

**Comment by firegreen** [comment]
![artwork5](https://user-images.githubusercontent.com/8926916/31910546-1fb38a04-b83e-11e7-8ca2-b7a013efbb2c.jpeg)

**Comment by yoanlcq** [comment]
Off the top of my head, and my personal view only : 
- I never actually imagined the dragon flying. He would have wings only for coolness; I see two problems with him flying : 
  1. He could just reach for the hero instead of waiting at its place;
  2. It's extra animation and kind of a lot of work, esp. if he's big and detailed.
- I'm assuming that panel 4 of the image where he resurrects illustrates the magnetic rails;
  As you drew it, it looks like a part of them lightens up when the guardian gets close, which is not a bad idea but I'm afraid it might hurt readability of the level (because rails wouldn't be lit up be default and the player might not clearly see them from afar).
  On the other hand, this might be one way to insert "hidden passages", etc.
  The thing is, I was always thinking that the whole rail would be emitting light at all times, AND when the hero gets close there's some extra FX like "hey look, it's related to you".
- I like the colors you've used in your last image, because they remind of our claimed _No Man's Sky_ influence, which I think we tend to forget (we mustn't ! Or otherwise it's still not too late to change CDCF) !
- I'm not clear about what "Magnet Control", "Propulsion Jump" and "Magnet Repulsion" are. CDCF says (for now, and as far as I understand (I might be wrong)) : 
  - We can choose to "get attracted to magnetic objects" (we reach for them);
  - We can do a simple jump;
  - An upgrade makes our punches also throw magnetic shockwaves which send enemies flying.
  I just suspect there might have been a misunderstanding somewhere and we should mind discussing it further to fix it.

Anyway good work there ! :+1: 
_(aaand I think you can tick some of dem checkboxes)_

**Comment by firegreen** [comment]
* The panel 4 doesn't show magnetic rails but some "tubes" which lead lights. This tube is enlightened for showing the way to the hero
* Magnet control is a mistake, I was thinking about the second capacity but I got wrong, It is actually "magnet wave" which is a distant attack 
* The "propulsion jump" and the "magnet repulsion" is potential new features which we may discuss

**Comment by yoanlcq** [comment]
> The "propulsion jump" and the "magnet repulsion" is potential new features which we may discuss

Like in the "potential extra features" section ? Otherwise yes we may - I just suspect we've got quite a lot going on already (at our scale). We'll see.

**Comment by yoanlcq** [comment]
@firegreen which remaining checkboxes are you planning to get busy with ?  
I'd volunteer to draft some ennemies based on @Hellowizz's designs which we agreed upon (for the most part).

Teacher said he wouldn't really mind if we didn't illustrate the story. I believe we somewhat had assigned that to Helo but we need to say clearly if we want to do it or not. My opinion: that would be cool, while not worth more than an hour to spend drawing on.  

Also what is the `moves` checkbox for ?

**Comment by firegreen** [comment]
Maybe i should make more places
I let you make Enemies
Moves is for illustrating the movement of an enemy (or of the hero)

**Comment by yoanlcq** [comment]
Ok, then if I am to draft ennemies, I might as well illustrate how they move around.  
Not sure if we need that for the hero though, since it moves like a regular bipedal humanoid.
