### ISSUE TITLE
Input mapping

### ISSUE THREAD

**Issue by firegreen** [imac2018-3d/StoneEdge#31]
Quoting @yoanlcq in #5 :
### Input Mapper
Handling gamepad input properly for all platforms is super hard, because the button numbers change from one OS to another.

**Comment by yoanlcq** [comment]
For posterity:

My latest changes include the `XbInput` class, for reliable cross-platform Xbox Controller input.  
It also includes `InputActions`, which supersedes our notion of the `InputMapper`.  
Last but not least, I've added "Raw Axes" in the project's Input Manager - these wrap accesses to raw controller axes and are required by `XbInput`.

`XbInput` needs to be tested on Linux and Mac OS X. I'm gonna do that ASAP but I'm quite confident since the info comes from [http://wiki.unity3d.com/index.php/Xbox360Controller](http://wiki.unity3d.com/index.php/Xbox360Controller).

**Comment by yoanlcq** [comment]
cc @CoralieGold - When working on settings, you'll be interested in `Se/InputActions.cs` which is the "Input Mapper" supposedly initialized by settings when they are loaded. ^^
